# from InputAndExpectedOutput import InputAndExpectedOutputForSinglePrompt
# from TestModelAccuracy import TestModelAccuracy
# from LLMCaller import OpenAILLM
# from PromptInputs import Event

# events = [
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Construction Site Work"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Cooking in a Restaurant Kitchen"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Operating Heavy Machinery"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Swimming in a Pool"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Driving on a Highway"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Playing Sports"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Working in an Office"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Using Power Tools"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Hiking in the Mountains"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Playing at a Playground"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Unsecured scaffolding"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Hot surfaces"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Mechanical malfunction"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Lack of lifeguard supervision"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Reckless drivers"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Lack of protective gear"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Improperly stored cables"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Electrical malfunction"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Unstable terrain"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Broken equipment"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Worker falling from scaffolding"), expected_output=True),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Chef burning hand on stove"), expected_output=True),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Operator caught in machinery"), expected_output=True),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Swimmer drowning"), expected_output=True),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Car collision"), expected_output=True),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Athlete getting hit in the head"), expected_output=True),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Employee tripping on cables"), expected_output=True),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Worker receiving electric shock"), expected_output=True),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Hiker slipping and falling"), expected_output=True),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Child falling off monkey bars"), expected_output=True),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Impact injury"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Burn injury"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Crushing injury"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Drowning"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Whiplash injury"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Concussion"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Fall injury"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Electric shock injury"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Sprained ankle or broken bone"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Fractured arm"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Construction workers"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Kitchen staff"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Machine operators"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Horse rider"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Stable hand"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Golf player"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Swimmers"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Drivers and passengers"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Athletes"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Office workers"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Construction workers, technicians"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Hikers"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Children"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Safety harness"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Oven mitts"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Emergency stop button"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Lifeguard supervision"), expected_output=False),
#     InputAndExpectedOutputForSinglePrompt(input=Event(input="Seatbelts"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Protective gear"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Cable management"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Electrical safety measures"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Proper footwear"), expected_output=False),
#     # InputAndExpectedOutputForSinglePrompt(input=Event(input="Safety barriers"), expected_output=False)
# ]

# if __name__ == "__main__":
    
#     test_accuracy = TestModelAccuracy(
#         LLM=OpenAILLM(),
#         LLM_name='gpt-3.5-turbo',
#         list_of_input_and_expected_outputs=events,
#         sheet_name='Events',
#         test_description='Evaluating prompt on Chat GPT generated data for events'
#         )
#     test_accuracy.run_test()